name: Run lint and test

on:
  workflow_dispatch:
    inputs:
      node_versions:
        description: 'Select Node versions'
        required: true
        default: '["20", "22", "23"]'
        type: choice
        options:
          - '["20"]'
          - '["22"]'
          - '["23"]'
          - '["20", "22", "23"]'
      os_version:
        description: 'Select OS'
        required: true
        default: '["ubuntu-latest"]'
        type: choice
        options:
          - '["ubuntu-latest"]'
          - '["windows-latest"]'
          - '["macos-latest"]'
      fail_fast:
        description: 'Use fail-fast'
        required: true
        type: boolean

jobs:
  test:
    name: Test (Node ${{ matrix.node-version }} on ${{ matrix.os }})
    strategy:
      fail-fast: ${{ inputs.fail_fast }}
      matrix:
        os: ${{ fromJSON(inputs.os_version) }}
        node-version: ${{ fromJSON(inputs.node_versions) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up NASM (for imagemin binary builds)
        uses: ilammy/setup-nasm@v1
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test:coverage
