name: Bump version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Semver bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    name: Bump package ${{ inputs.semver }} version
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up NASM (for imagemin binary builds)
        uses: ilammy/setup-nasm@v1
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Set Git user
        run: |
          git config --global user.name 'vHeemstra'
          git config --global user.email '17368112+vHeemstra@users.noreply.github.com'

      - run: npm ci

      - name: Major version
        if: ${{ inputs.semver == 'major' }}
        run: npm run bump:major
      - name: Minor version
        if: ${{ inputs.semver == 'minor' }}
        run: npm run bump:minor
      - name: Patch version
        if: ${{ inputs.semver == 'patch' }}
        run: npm run bump:patch

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
